### ISSUE TITLE
Add an option to use KNetCompactedReplicator

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KEFCore#60]
**Is your feature request related to a problem? Please describe.**
The tables are stored within topics using the key for Primary Key and value for all items, so it is possible to use [KNetCompactedReplicator](https://github.com/masesgroup/KNet/blob/master/src/net/KNet/Specific/KNetCompactedReplicator.cs) to manage the compacted topics.

**Describe the solution you'd like**
Add an options to choose between [KNetCompactedReplicator](https://github.com/masesgroup/KNet/blob/master/src/net/KNet/Specific/KNetCompactedReplicator.cs) and Apache Kafka Streams to retrieve the data from the topics.

**Describe alternatives you've considered**
N/A

**Additional context**
The types associated to [KNetCompactedReplicator](https://github.com/masesgroup/KNet/blob/master/src/net/KNet/Specific/KNetCompactedReplicator.cs) shall be managed like in #59

**Comment by masesdevelopers** [comment]
#59 will be applied later, the modification starts using `KNetCompactedReplicator<string, string>`

**Comment by masesdevelopers** [comment]
[KNetCompactedReplicator](https://github.com/masesgroup/KNet/blob/master/src/net/KNet/Specific/KNetCompactedReplicator.cs) shall be enhanced to cover some needs of KEFCore:
- Add a flag, like `IsStarted`, indicating if the instance is started
- Add a way to understand if the instance is in sync with the topic
- Add a way to store keys, along with some metadata (offset, timestamp, etc), to avoid the local storage of values

**Comment by masesdevelopers** [comment]
Using [KNetCompactedReplicator](https://github.com/masesgroup/KNet/blob/master/src/net/KNet/Specific/KNetCompactedReplicator.cs) when 
https://github.com/masesgroup/KNet/blob/5ab24481744db62c8ded79b7e7ec5c5f6c0e8f74/src/net/KNet/Specific/KNetCompactedReplicator.cs#L269 
is invoked it raises a `System.ArgumentNullException` in 
https://github.com/masesgroup/KNet/blob/5ab24481744db62c8ded79b7e7ec5c5f6c0e8f74/src/net/KNet/Specific/Producer/KNetProducer.cs#L406
